<?php if ($this->drives): ?>
<ul class="stdl">
    <?php foreach ($this->drives as $drive): ?>
    <li id="drive-<?= $drive['drive_id'] ?>">
        <div class="data">
            <h4 class="title"><?= $drive['name'] ?></h4>
            <?php if ($drive['description']): ?>
            <div class="desc"><?= $this->escape($drive['description']) ?></div>
            <?php endif; ?>
            <dl class="meta">
                <dt>Właściciel:</dt>
                <dd><?= $this->fullName($drive['owner']) ?></dd>
                <dt>Utworzony:</dt>
                <dd class="timelog">
                    <span class="tm"><?= date('j M Y, H:i', strtotime($drive['create_time'])) ?></span>
                    <span class="sep">przez</span>
                    <span class="user"><?= $this->fullName($drive['created_by']) ?></span>
                </dd>
                <dt>Zajęte miejsce:</dt>
                <dd><?= $this->fileSize($drive['disk_usage']) ?>
                <?php if ($drive['quota']): ?>
                    / <?= $this->fileSize($drive['quota']) ?>
                    <?php $ratio = $drive['disk_usage'] / $drive['quota'] ?>
                    <?php if ($ratio < 0.75): ?>
                        <?php $class = 'ok'; ?>
                    <?php elseif ($ratio < 0.9): ?>
                        <?php $class = 'warning'; ?>
                    <?php else: ?>
                        <?php $class = 'danger'; ?>
                    <?php endif ?>
                        <div class="progress-bar ib" style="width:120px;margin-left:12px;">
                            <span class="bar bar-{{ class }}" style="width:{{ max(2, min(100, ratio * 100)) }}%"></span>
                        </div> <?= round($ratio * 100, 2) ?> %
                <?php endif ?>
                </dd>
            </dl>
        </div>
        <div class="actions">
        <?php if ($drive['url_edit']): ?>
        <a data-url="<?= $drive['url_edit'] ?>" class="opbtn drive-edit"><span>Edytuj<span class="icon edit"></span></span></a>
        <?php endif; ?>
        <a href="<?= $drive['url_browse'] ?>" class="opbtn"><span>Przeglądaj<span class="icon goto"></span></span></a>
        </div>
    </li>
    <?php endforeach; ?>
</ul>
<?php else: ?>
Brak dysków.
<?php endif; ?>
