ALTER TABLE {PREFIX}drive_dirs ADD COLUMN is_system TINYINT(1) NOT NULL DEFAULT 0 AFTER parent_id;
ALTER TABLE {PREFIX}drive_dirs ADD COLUMN is_readonly TINYINT(1) NOT NULL DEFAULT 0 AFTER is_system;
ALTER TABLE {PREFIX}drive_dirs ADD COLUMN is_hidden TINYINT(1) NOT NULL DEFAULT 0 AFTER is_readonly;

ALTER TABLE {PREFIX}drive_dirs ADD COLUMN system_count INTEGER UNSIGNED NOT NULL DEFAULT 0 AFTER is_hidden;

ALTER TABLE {PREFIX}drive_dirs ADD COLUMN handler VARCHAR(32);
