ALTER TABLE {PREFIX}drive_dirs ADD COLUMN is_system SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE {PREFIX}drive_dirs ADD COLUMN is_readonly SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE {PREFIX}drive_dirs ADD COLUMN is_hidden SMALLINT NOT NULL DEFAULT 0;

ALTER TABLE {PREFIX}drive_dirs ADD COLUMN system_count INTEGER NOT NULL DEFAULT 0 CHECK (system_count >= 0);

ALTER TABLE {PREFIX}drive_dirs ADD COLUMN handler VARCHAR(32);
