<?php if ($this->drives) { ?>
<ul class="stdl">
<?php   foreach ($this->drives as $drive) { ?>
 <li id="drive-<?= (int) $drive['id'] ?>">
  <div class="data">
   <h4 class="title"><?= $this->escape($drive['name']) ?></h4>
<?php     if ($drive['description']) { ?>
   <div class="desc"><?= $this->escape($drive['description']) ?></div>
<?php     } ?>
   <dl class="meta">
    <dt>Właściciel:</dt>
    <dd><?= $this->fn($drive['owner']) ?></dd>
    <dt>Utworzony:</dt>
    <dd class="timelog">
        <span class="tm"><?= $this->dateFormat($drive['create_time'], 'long', 'medium') ?></span>
        <span class="sep">przez</span>
        <span class="user"><?= $this->fn($drive['created_by']) ?></span>
    </dd>
    <dt>Zajęte miejsce:</dt>
    <dd><?= $this->fileSize($drive['disk_usage']) ?>
<?php if ($drive['quota']) { ?> / <?= $this->fileSize($drive['quota']) ?>
<?php
        $ratio = $drive['disk_usage'] / $drive['quota'];
        if ($ratio < .75) {
            $class = 'ok';
        } else if ($ratio < .9) {
            $class = 'warning';
        } else {
            $class = 'danger';
        }
?>
     <div class="progress-bar ib" style="width:120px;margin-left:12px;">
      <span class="bar bar-<?= $class ?>" style="width:<?= max(2, min(100, $ratio * 100)) ?>%"></span>
     </div> <?= round($ratio * 100, 2) ?> %
<?php } ?>
    </dd>
   </dl>
  </div>
  <div class="actions">
<?php if (isset($drive['url_edit'])) { ?>
   <a data-url="<?= $drive['url_edit'] ?>" class="opbtn drive-edit"><span>Edytuj<span class="icon edit"></span></span></a>
<?php } ?>
   <a href="<?= $drive['url_browse'] ?>" class="opbtn"><span>Przeglądaj<span class="icon goto"></span></span></a>
  </div>
 </li>
<?php   } ?>
</ul>
<?php } else { ?>
Brak dysków.
<?php } ?>
