<div id="drive-dir-browser"></div>
<style type="text/css"><?php include __DIR__ . '/temp.css' ?></style>
<script type="text/javascript" src="<?= $this->baseUrl('/js/mustache.min.js') ?>"></script>
<script type="text/javascript" src="<?= $this->baseUrl('/js/drive.js') ?>"></script>
<script type="text/javascript">
$(function() {
    new Drive.DirBrowser('#drive-dir-browser', <?= Zend_Json::encode(array(
        'uriTemplates' => $this->uri_templates,
        'dirId' => $this->dir_id,
        'breadcrumbs' => isset($this->dir_browser_breadcrumbs) ? $this->dir_browser_breadcrumbs : '#breadcrumbs',
        'disableAuxmenu' => isset($this->dir_browser_disable_auxmenu) && $this->dir_browser_disable_auxmenu,
        'disableUpdir' => isset($this->dir_browser_disable_updir) && $this->dir_browser_disable_updir,
    )) ?>);
});
</script>
