<?php $this->headLink()->appendStylesheet($this->moduleAsset('css/drive.css', 'maniple-drive')) ?>
<div id="breadcrumbs"></div>
<style>
#breadcrumbs .separator:before {
    content: '/';
}
</style>
<div id="drive-dir-browser"></div>

<script type="text/javascript">
$(function() {
    require(['<?= $this->drive()->jsLib() ?>'], function (Drive) {
        new Drive.DirBrowser('#drive-dir-browser', <?= Zefram_Json::encode(array(
            'uriTemplates'   => $this->uri_templates,
            'breadcrumbs'    => $this->dir_browser_breadcrumbs ? $this->dir_browser_breadcrumbs : '#breadcrumbs',
            'disableAuxmenu' => $this->dir_browser_disable_auxmenu,
            'disableUpdir'   => $this->dir_browser_disable_updir,
            'userSearchUrl'  => $this->user_search_url,
            'dir'            => $this->dir
        )) ?>);
    });
});
</script>
